### ISSUE TITLE
Instead of no score, switch to No Fail

### ISSUE THREAD

**Issue by queengooborg** [Zingabopp/BailOutMode#7]
Something that's been bugging me about this mod is the way that it doesn't save scores in general.  It would be great if, rather than simply not saving the score, it switches to the behavior of vanilla No Fail, dividing the scrore in half.  That way, if I'm playing a song that's just a little too challenging for me to beat consistently, I can still have a score that I can reference back to and see that I'm improving.  It would be great to have this functionality implemented, possibly as a config switch!

(I can see the possibility that mods are forbidden from modifying a score to prevent cheats.  If so, no worries.)

**Comment by Zingabopp** [comment]
That's a pretty gray area, so I probably won't straight up switch it to No-Fail. I might provide an option to save the score locally though (I actually did extra so it wouldn't save the score locally).
